/**
 * Parity tests: verify that the claude-code Provider adapter produces
 * byte-identical output to the legacy parseJsonlContent() for every
 * fixture session.  If any test here fails, the adapter has diverged
 * from the legacy parser and Phase B cannot proceed.
 *
 * Each fixture is:
 *  1. Parsed by the legacy parser (parseJsonlContent) → reference rows
 *  2. Read through createClaudeCodeProvider().readSession() → rows via native
 *  3. Both are stable-stringified and compared character-by-character
 *
 * The expected.json snapshots in tests/fixtures/parity/ were generated by
 * scripts/generate-parity-snapshots.mjs using the same legacy parser, so
 * a three-way comparison (legacy == snapshot == provider) is guaranteed when
 * the snapshot file is current.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';

import { parseJsonlContent } from '../../src/shared/parser.js';
import { createClaudeCodeProvider } from '../../src/shared/providers/claude-code.js';
import type { WaterfallRow } from '../../src/shared/types.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(__dirname, '../fixtures');
const parityDir = join(fixturesDir, 'parity');

// ---------------------------------------------------------------------------
// Stable stringify (mirrors scripts/generate-parity-snapshots.mjs)
// ---------------------------------------------------------------------------

function stableStringify(value: unknown): string {
  if (Array.isArray(value)) {
    return '[' + (value as unknown[]).map(stableStringify).join(',') + ']';
  }
  if (value !== null && typeof value === 'object') {
    const keys = Object.keys(value as object).sort();
    const pairs = keys.map(
      (k) => JSON.stringify(k) + ':' + stableStringify((value as Record<string, unknown>)[k]),
    );
    return '{' + pairs.join(',') + '}';
  }
  return JSON.stringify(value);
}

// ---------------------------------------------------------------------------
// Fixture definitions
// ---------------------------------------------------------------------------

interface ParityFixture {
  /** JSONL file under tests/fixtures/ */
  fixture: string;
  /** Expected snapshot under tests/fixtures/parity/ */
  snapshot: string;
}

const FIXTURES: ParityFixture[] = [
  { fixture: 'simple-session.jsonl',          snapshot: 'simple-session.expected.json' },
  { fixture: 'session-with-agents.jsonl',      snapshot: 'session-with-agents.expected.json' },
  { fixture: 'session-with-errors.jsonl',      snapshot: 'session-with-errors.expected.json' },
  { fixture: 'session-with-compaction.jsonl',  snapshot: 'session-with-compaction.expected.json' },
  { fixture: 'session-with-failure.jsonl',     snapshot: 'session-with-failure.expected.json' },
  { fixture: 'session-with-api-error.jsonl',   snapshot: 'session-with-api-error.expected.json' },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Fake file-system layout expected by createClaudeCodeProvider. */
const FAKE_PROJECT_SLUG = 'parity-project';

/**
 * Set up an in-memory provider that serves a single fixture file.
 * Because the provider does real fs reads, we point claudeHome at a
 * temporary directory populated with the fixture's content.
 *
 * Simpler: read the file content directly with parseJsonlContent, then
 * compare with the provider's output that reads the same physical file.
 * We achieve this by pointing the provider at the real fixtures directory,
 * treating each fixture as a session under a pseudo project slug.
 */

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe('provider parity: claude-code adapter vs legacy parser', () => {
  // Point the provider at a specially constructed fixtures layout.
  // tests/fixtures/parity-project/<session>.jsonl
  // We create the provider to serve from the actual fixtures directory.
  // The session id is '<fixtureStem>/<fixtureStem>' to match the provider's
  // '<projectSlug>/<sessionId>' format where we use the fixtures dir as
  // the claudeHome and the fixture stem as both slug and sessionId.
  //
  // Layout we exploit:
  //   claudeHome = tests/fixtures (so projectsDir = tests/fixtures/projects)
  //
  // Since the fixtures aren't in a `projects/` sub-dir we use a thin shim:
  // we read the content directly with parseJsonlContent for the reference,
  // and read via the provider that uses a real temp dir with symlinks — but
  // that's too complex for a parity test.
  //
  // Simpler approach: create the provider with claudeHome=fixturesDir and
  // put the fixture in fixturesDir/projects/<slug>/<session>.jsonl by
  // treating fixturesDir/parity as the projects sub-dir.  Instead, we just
  // test parity by calling readSession with a provider that maps directly.
  //
  // Most direct approach: use a custom claudeHome that IS the fixtures dir,
  // then the provider reads from fixtures/projects/<slug>/<id>.jsonl.
  // We already have fixtures/parity/ — but that's snapshots.
  //
  // Final plan: create the provider with claudeHome pointing at a temp
  // directory we build on the fly, populated with symlinks. But node:fs/promises
  // doesn't have symlink in a portable way here.
  //
  // SIMPLEST correct plan:
  //   - Read fixture content with readFileSync → reference via parseJsonlContent
  //   - Write fixture to a tmp path under OS tmpdir
  //   - Point provider at that tmpdir
  //   - Call readSession('<slug>/<id>')
  //   - Compare stableStringify outputs
  //
  // We do this setup once per fixture below.

  for (const { fixture, snapshot } of FIXTURES) {
    const fixturePath = join(fixturesDir, fixture);
    const snapshotPath = join(parityDir, snapshot);

    it(`fixture: ${fixture}`, async () => {
      // ---- 1. Reference: legacy parser ----
      const content = readFileSync(fixturePath, 'utf-8');
      const legacyRows = parseJsonlContent(content);
      const legacyStr = stableStringify(legacyRows);

      // ---- 2. Snapshot: pre-generated expected.json ----
      expect(
        existsSync(snapshotPath),
        `Snapshot file missing: ${snapshotPath}. Run scripts/generate-parity-snapshots.mjs`,
      ).toBe(true);
      const snapshotStr = readFileSync(snapshotPath, 'utf-8');

      // Snapshot must match legacy parser (validates snapshot is fresh)
      expect(legacyStr).toBe(snapshotStr);

      // ---- 3. Provider: createClaudeCodeProvider ----
      // Build a fake claudeHome in OS tmpdir containing exactly this fixture.
      const { mkdtempSync, writeFileSync, mkdirSync } = await import('node:fs');
      const { tmpdir } = await import('node:os');

      const tmpHome = mkdtempSync(join(tmpdir(), 'noctrace-parity-'));
      const slug = 'test-project';
      const sessionId = fixture.replace('.jsonl', '');
      const projectDir = join(tmpHome, 'projects', slug);
      mkdirSync(projectDir, { recursive: true });
      writeFileSync(join(projectDir, `${sessionId}.jsonl`), content, 'utf-8');

      const provider = createClaudeCodeProvider(tmpHome);
      const session = await provider.readSession(`${slug}/${sessionId}`);
      const providerStr = stableStringify(session.native as WaterfallRow[]);

      // Provider native output must match the legacy parser output byte-for-byte
      expect(providerStr).toBe(legacyStr);

      // Cleanup
      const { rmSync } = await import('node:fs');
      rmSync(tmpHome, { recursive: true, force: true });
    });
  }
});
